language: cpp
sudo: required
dist: bionic

branches:
  only:
    - master

before_install:
  - sudo apt update
  - sudo apt -y install libsdl2-dev

install:
  - pip install --user cmake
  - 

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make -j7