#pragma once 

typedef enum CBCode {
    CB_Code_RLC_B = 0x00,
    CB_Code_RLC_C,
    CB_Code_RLC_D,
    CB_Code_RLC_E,
    CB_Code_RLC_H,
    CB_Code_RLC_L,
    CB_Code_RLC_ADDR_HL,
    CB_Code_RLC_A,

    CB_Code_RRC_B,
    CB_Code_RRC_C,
    CB_Code_RRC_D,
    CB_Code_RRC_E,
    CB_Code_RRC_H,
    CB_Code_RRC_L,
    CB_Code_RRC_ADDR_HL,
    CB_Code_RRC_A,

    CB_Code_RL_B = 0X10,
    CB_Code_RL_C,
    CB_Code_RL_D,
    CB_Code_RL_E,
    CB_Code_RL_H,
    CB_Code_RL_L,
    CB_Code_RL_ADDR_HL,
    CB_Code_RL_A,

    CB_Code_RR_B,
    CB_Code_RR_C,
    CB_Code_RR_D,
    CB_Code_RR_E,
    CB_Code_RR_H,
    CB_Code_RR_L,
    CB_Code_RR_ADDR_HL,
    CB_Code_RR_A,

    CB_Code_SLA_B = 0X20,
    CB_Code_SLA_C,
    CB_Code_SLA_D,
    CB_Code_SLA_E,
    CB_Code_SLA_H,
    CB_Code_SLA_L,
    CB_Code_SLA_ADDR_HL,
    CB_Code_SLA_A,

    CB_Code_SRA_B,
    CB_Code_SRA_C,
    CB_Code_SRA_D,
    CB_Code_SRA_E,
    CB_Code_SRA_H,
    CB_Code_SRA_L,
    CB_Code_SRA_ADDR_HL,
    CB_Code_SRA_A,

    CB_Code_SWAP_B = 0X30,
    CB_Code_SWAP_C, 
    CB_Code_SWAP_D,
    CB_Code_SWAP_E,
    CB_Code_SWAP_H,
    CB_Code_SWAP_L,
    CB_Code_SWAP_ADDR_HL,
    CB_Code_SWAP_A,

    CB_Code_SRL_B,
    CB_Code_SRL_C,
    CB_Code_SRL_D,
    CB_Code_SRL_E,
    CB_Code_SRL_H,
    CB_Code_SRL_L,
    CB_Code_SRL_ADDR_HL,
    CB_Code_SRL_A,

    CB_Code_BIT_0_B = 0X40,
    CB_Code_BIT_0_C,
    CB_Code_BIT_0_D,
    CB_Code_BIT_0_E,
    CB_Code_BIT_0_H,
    CB_Code_BIT_0_L,
    CB_Code_BIT_0_ADDR_HL,
    CB_Code_BIT_0_A,

    CB_Code_BIT_1_B,
    CB_Code_BIT_1_C,
    CB_Code_BIT_1_D,
    CB_Code_BIT_1_E,
    CB_Code_BIT_1_H,
    CB_Code_BIT_1_L,
    CB_Code_BIT_1_ADDR_HL,
    CB_Code_BIT_1_A,

    CB_Code_BIT_2_B = 0X50,
    CB_Code_BIT_2_C,
    CB_Code_BIT_2_D,
    CB_Code_BIT_2_E,
    CB_Code_BIT_2_H,
    CB_Code_BIT_2_L,
    CB_Code_BIT_2_ADDR_HL,
    CB_Code_BIT_2_A,

    CB_Code_BIT_3_B,
    CB_Code_BIT_3_C,
    CB_Code_BIT_3_D,
    CB_Code_BIT_3_E,
    CB_Code_BIT_3_H,
    CB_Code_BIT_3_L,
    CB_Code_BIT_3_ADDR_HL,
    CB_Code_BIT_3_A,

    CB_Code_BIT_4_B = 0X60,
    CB_Code_BIT_4_C,
    CB_Code_BIT_4_D,
    CB_Code_BIT_4_E,
    CB_Code_BIT_4_H,
    CB_Code_BIT_4_L,
    CB_Code_BIT_4_ADDR_HL,
    CB_Code_BIT_4_A,

    CB_Code_BIT_5_B,
    CB_Code_BIT_5_C,
    CB_Code_BIT_5_D,
    CB_Code_BIT_5_E,
    CB_Code_BIT_5_H,
    CB_Code_BIT_5_L,
    CB_Code_BIT_5_ADDR_HL,
    CB_Code_BIT_5_A,

    CB_Code_BIT_6_B = 0X70,
    CB_Code_BIT_6_C,
    CB_Code_BIT_6_D,
    CB_Code_BIT_6_E,
    CB_Code_BIT_6_H,
    CB_Code_BIT_6_L,
    CB_Code_BIT_6_ADDR_HL,
    CB_Code_BIT_6_A,

    CB_Code_BIT_7_B,
    CB_Code_BIT_7_C,
    CB_Code_BIT_7_D,
    CB_Code_BIT_7_E,
    CB_Code_BIT_7_H,
    CB_Code_BIT_7_L,
    CB_Code_BIT_7_ADDR_HL,
    CB_Code_BIT_7_A,

    CB_Code_RES_0_B = 0X80,
    CB_Code_RES_0_C,
    CB_Code_RES_0_D,
    CB_Code_RES_0_E,
    CB_Code_RES_0_H,
    CB_Code_RES_0_L,
    CB_Code_RES_0_ADDR_HL,
    CB_Code_RES_0_A,

    CB_Code_RES_1_B,    
    CB_Code_RES_1_C,
    CB_Code_RES_1_D,
    CB_Code_RES_1_E,
    CB_Code_RES_1_H,
    CB_Code_RES_1_L,
    CB_Code_RES_1_ADDR_HL,
    CB_Code_RES_1_A,

    CB_Code_RES_2_B = 0X90,
    CB_Code_RES_2_C,
    CB_Code_RES_2_D,
    CB_Code_RES_2_E,
    CB_Code_RES_2_H,
    CB_Code_RES_2_L,
    CB_Code_RES_2_ADDR_HL,
    CB_Code_RES_2_A,

    CB_Code_RES_3_B,
    CB_Code_RES_3_C,
    CB_Code_RES_3_D,
    CB_Code_RES_3_E,
    CB_Code_RES_3_H,
    CB_Code_RES_3_L,
    CB_Code_RES_3_ADDR_HL,
    CB_Code_RES_3_A,
    
    CB_Code_RES_4_B = 0XA0,
    CB_Code_RES_4_C,
    CB_Code_RES_4_D,
    CB_Code_RES_4_E,
    CB_Code_RES_4_H,
    CB_Code_RES_4_L,
    CB_Code_RES_4_ADDR_HL,
    CB_Code_RES_4_A,

    CB_Code_RES_5_B,
    CB_Code_RES_5_C,
    CB_Code_RES_5_D,
    CB_Code_RES_5_E,
    CB_Code_RES_5_H,
    CB_Code_RES_5_L,
    CB_Code_RES_5_ADDR_HL,
    CB_Code_RES_5_A,

    CB_Code_RES_6_B = 0XB0,
    CB_Code_RES_6_C,
    CB_Code_RES_6_D,
    CB_Code_RES_6_E,
    CB_Code_RES_6_H,
    CB_Code_RES_6_L,
    CB_Code_RES_6_ADDR_HL,
    CB_Code_RES_6_A,

    CB_Code_RES_7_B,
    CB_Code_RES_7_C,
    CB_Code_RES_7_D,
    CB_Code_RES_7_E,
    CB_Code_RES_7_H,
    CB_Code_RES_7_L,
    CB_Code_RES_7_ADDR_HL,
    CB_Code_RES_7_A,

    CB_Code_SET_0_B = 0XC0,
    CB_Code_SET_0_C,
    CB_Code_SET_0_D,
    CB_Code_SET_0_E,
    CB_Code_SET_0_H,
    CB_Code_SET_0_L,
    CB_Code_SET_0_ADDR_HL,
    CB_Code_SET_0_A,

    CB_Code_SET_1_B,
    CB_Code_SET_1_C,
    CB_Code_SET_1_D,
    CB_Code_SET_1_E,
    CB_Code_SET_1_H,
    CB_Code_SET_1_L,
    CB_Code_SET_1_ADDR_HL,
    CB_Code_SET_1_A,

    CB_Code_SET_2_B = 0XD0,
    CB_Code_SET_2_C,
    CB_Code_SET_2_D,
    CB_Code_SET_2_E,
    CB_Code_SET_2_H,
    CB_Code_SET_2_L,
    CB_Code_SET_2_ADDR_HL,
    CB_Code_SET_2_A,

    CB_Code_SET_3_B,
    CB_Code_SET_3_C,
    CB_Code_SET_3_D,
    CB_Code_SET_3_E,
    CB_Code_SET_3_H,
    CB_Code_SET_3_L,
    CB_Code_SET_3_ADDR_HL,
    CB_Code_SET_3_A,

    CB_Code_SET_4_B = 0XE0,
    CB_Code_SET_4_C,
    CB_Code_SET_4_D,
    CB_Code_SET_4_E,
    CB_Code_SET_4_H,
    CB_Code_SET_4_L,
    CB_Code_SET_4_ADDR_HL,
    CB_Code_SET_4_A,

    CB_Code_SET_5_B,
    CB_Code_SET_5_C,
    CB_Code_SET_5_D,
    CB_Code_SET_5_E,
    CB_Code_SET_5_H,
    CB_Code_SET_5_L,
    CB_Code_SET_5_ADDR_HL,
    CB_Code_SET_5_A,

    CB_Code_SET_6_B = 0XF0,
    CB_Code_SET_6_C, 
    CB_Code_SET_6_D,
    CB_Code_SET_6_E,
    CB_Code_SET_6_H,
    CB_Code_SET_6_L,
    CB_Code_SET_6_ADDR_HL,
    CB_Code_SET_6_A,

    CB_Code_SET_7_B,
    CB_Code_SET_7_C,
    CB_Code_SET_7_D,
    CB_Code_SET_7_E,
    CB_Code_SET_7_H,
    CB_Code_SET_7_L,
    CB_Code_SET_7_ADDR_HL,
    CB_Code_SET_7_A,
} CB_Code;  